#!/usr/bin/env python3
"""Refresh YouTube cookies for the Indexframe yt-dlp demo and upload to GCP.

This script intentionally uses a dedicated Playwright browser profile instead
of reading cookies from a user's normal browser. First run: a visible Chromium
window opens and you sign in with the demo YouTube/Google account. Later runs
reuse that profile, refresh the YouTube session, export Netscape cookies.txt,
and optionally upload it to Secret Manager through gcloud.

Typical use:
  python refresh_youtube_cookies.py \
    --project dev-indexframe \
    --secret-name indexframe-youtube-cookies \
    --update-cloud-run-job \
    --job-name indexframe-poc \
    --region us-central1

Local Docker smoke test after export:
  docker run --rm \
    -v "$PWD/.indexframe-youtube-cookies.txt:/secrets/youtube-cookies.txt:ro" \
    -e YT_DLP_COOKIES_FILE=/secrets/youtube-cookies.txt \
    indexframe-cookie-poc \
    python -u indexframe_poc.py --url 'https://www.youtube.com/watch?v=VIDEO_ID' --out-dir /tmp/indexframe-run --skip-gemini
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

YOUTUBE_HOME = "https://www.youtube.com/"
YOUTUBE_SIGNIN = "https://accounts.google.com/ServiceLogin?service=youtube&continue=https%3A%2F%2Fwww.youtube.com%2F"
DEFAULT_PROFILE_DIR = ".indexframe-youtube-profile"
DEFAULT_COOKIE_FILE = ".indexframe-youtube-cookies.txt"
DEFAULT_SECRET_NAME = "indexframe-youtube-cookies"
DEFAULT_SECRET_MOUNT = "/secrets/youtube-cookies.txt"
AUTH_COOKIE_NAMES = {
    "SID",
    "HSID",
    "SSID",
    "APISID",
    "SAPISID",
    "__Secure-1PSID",
    "__Secure-3PSID",
    "__Secure-1PSIDTS",
    "__Secure-3PSIDTS",
}


def log(message: str) -> None:
    print(f"[youtube-cookies] {message}", flush=True)


def run(cmd: List[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    log("$ " + " ".join(cmd))
    return subprocess.run(cmd, check=check, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)


def import_playwright() -> Any:
    try:
        from playwright.sync_api import TimeoutError as PlaywrightTimeoutError  # type: ignore
        from playwright.sync_api import sync_playwright  # type: ignore
    except Exception as exc:  # pragma: no cover - user environment dependent
        raise SystemExit(
            "Playwright is not installed. Run:\n"
            "  pip install -r requirements.indexframe.txt\n"
            "  python -m playwright install chromium"
        ) from exc
    return sync_playwright, PlaywrightTimeoutError


def cookie_domain(cookie: Dict[str, Any]) -> str:
    return str(cookie.get("domain") or "")


def looks_authenticated(cookies: Iterable[Dict[str, Any]]) -> bool:
    for cookie in cookies:
        domain = cookie_domain(cookie).lower()
        name = str(cookie.get("name") or "")
        if name in AUTH_COOKIE_NAMES and ("youtube.com" in domain or "google.com" in domain):
            return True
    return False


def is_relevant_cookie(cookie: Dict[str, Any]) -> bool:
    # Keep Google + YouTube cookies from this dedicated Playwright profile. These
    # are the domains yt-dlp commonly needs for authenticated YouTube requests.
    domain = cookie_domain(cookie).lower()
    return (
        "youtube.com" in domain
        or "google.com" in domain
        or "google.co." in domain
        or "googleusercontent.com" in domain
        or "gstatic.com" in domain
    )


def netscape_bool(value: bool) -> str:
    return "TRUE" if value else "FALSE"


def normalise_expires(value: Any) -> int:
    try:
        expires = int(float(value))
    except Exception:
        return 0
    return max(0, expires)


def write_netscape_cookie_file(cookies: Iterable[Dict[str, Any]], path: Path) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    rows: List[str] = [
        "# Netscape HTTP Cookie File",
        "# Generated by refresh_youtube_cookies.py for Indexframe demo yt-dlp usage.",
        "# Treat this file like a password. Do not commit it.",
    ]
    count = 0
    for cookie in sorted(cookies, key=lambda c: (cookie_domain(c), str(c.get("name") or ""))):
        if not is_relevant_cookie(cookie):
            continue
        domain = cookie_domain(cookie)
        if not domain:
            continue
        include_subdomains = domain.startswith(".")
        path_value = str(cookie.get("path") or "/")
        secure = bool(cookie.get("secure"))
        expires = normalise_expires(cookie.get("expires"))
        name = str(cookie.get("name") or "")
        value = str(cookie.get("value") or "")
        if not name:
            continue
        # Netscape cookie files are tab-delimited and one cookie per line.
        safe_value = value.replace("\n", "").replace("\r", "")
        rows.append(
            "\t".join(
                [
                    domain,
                    netscape_bool(include_subdomains),
                    path_value,
                    netscape_bool(secure),
                    str(expires),
                    name,
                    safe_value,
                ]
            )
        )
        count += 1
    path.write_text("\n".join(rows) + "\n", encoding="utf-8")
    try:
        path.chmod(0o600)
    except Exception:
        pass
    return count


def refresh_cookie_file(*, profile_dir: Path, cookie_file: Path, headless: bool, force_login: bool, wait_seconds: float, install_browser_on_missing: bool) -> int:
    sync_playwright, PlaywrightTimeoutError = import_playwright()
    profile_dir.mkdir(parents=True, exist_ok=True)

    with sync_playwright() as p:
        try:
            context = p.chromium.launch_persistent_context(
                user_data_dir=str(profile_dir),
                headless=headless,
                viewport={"width": 1365, "height": 900},
                args=["--disable-blink-features=AutomationControlled"],
            )
        except Exception as exc:  # pragma: no cover - browser install dependent
            if not install_browser_on_missing:
                raise SystemExit(
                    "Could not launch Playwright Chromium. Run:\n"
                    "  python -m playwright install chromium\n"
                    f"Original error: {exc}"
                ) from exc
            log("Playwright Chromium is missing or not launchable; installing chromium browser bundle once.")
            run([sys.executable, "-m", "playwright", "install", "chromium"])
            try:
                context = p.chromium.launch_persistent_context(
                    user_data_dir=str(profile_dir),
                    headless=headless,
                    viewport={"width": 1365, "height": 900},
                    args=["--disable-blink-features=AutomationControlled"],
                )
            except Exception as retry_exc:
                raise SystemExit(
                    "Could not launch Playwright Chromium after installation. On Linux, run:\n"
                    "  python -m playwright install --with-deps chromium\n"
                    f"Original error: {retry_exc}"
                ) from retry_exc

        page = context.pages[0] if context.pages else context.new_page()
        target_url = YOUTUBE_SIGNIN if force_login else YOUTUBE_HOME
        log(f"opening {target_url}")
        try:
            page.goto(target_url, wait_until="domcontentloaded", timeout=60000)
        except PlaywrightTimeoutError:
            log("initial page load timed out; continuing with current browser state")

        if wait_seconds > 0:
            time.sleep(wait_seconds)

        cookies = context.cookies()
        if force_login or not looks_authenticated(cookies):
            if headless:
                context.close()
                raise SystemExit(
                    "No authenticated YouTube/Google cookies found and --headless was used. "
                    "Run once without --headless and sign in to the demo account."
                )
            log("No authenticated YouTube cookies found yet.")
            log("Sign in with the demo account in the Chromium window, then return here and press Enter.")
            try:
                page.goto(YOUTUBE_SIGNIN, wait_until="domcontentloaded", timeout=60000)
            except PlaywrightTimeoutError:
                pass
            input("Press Enter after YouTube shows the signed-in demo account... ")
            try:
                page.goto(YOUTUBE_HOME, wait_until="networkidle", timeout=60000)
            except PlaywrightTimeoutError:
                log("YouTube did not reach networkidle; continuing after DOM load.")
            cookies = context.cookies()

        if not looks_authenticated(cookies):
            context.close()
            raise SystemExit(
                "Could not find expected YouTube/Google auth cookies after login. "
                "Check that the browser is signed into the demo account and try again."
            )

        count = write_netscape_cookie_file(cookies, cookie_file)
        context.close()
    if count == 0:
        raise SystemExit("Exported zero relevant cookies; not uploading.")
    log(f"wrote {count} cookies to {cookie_file}")
    return count


def require_project(project: str) -> str:
    resolved = project or os.getenv("PROJECT_ID") or os.getenv("GOOGLE_CLOUD_PROJECT") or os.getenv("GCP_PROJECT")
    if not resolved:
        raise SystemExit("Set --project or PROJECT_ID/GOOGLE_CLOUD_PROJECT before uploading to Secret Manager.")
    return resolved


def ensure_secret(project: str, secret_name: str) -> None:
    described = run(["gcloud", "secrets", "describe", secret_name, "--project", project], check=False)
    if described.returncode == 0:
        return
    run([
        "gcloud",
        "secrets",
        "create",
        secret_name,
        "--replication-policy=automatic",
        "--project",
        project,
    ])


def upload_secret_version(project: str, secret_name: str, cookie_file: Path) -> None:
    ensure_secret(project, secret_name)
    run([
        "gcloud",
        "secrets",
        "versions",
        "add",
        secret_name,
        f"--data-file={cookie_file}",
        "--project",
        project,
    ])
    log(f"uploaded {cookie_file} to Secret Manager secret {secret_name}:latest")


def grant_secret_access(project: str, secret_name: str, service_account: str) -> None:
    if not service_account:
        return
    member = service_account if service_account.startswith("serviceAccount:") else f"serviceAccount:{service_account}"
    run([
        "gcloud",
        "secrets",
        "add-iam-policy-binding",
        secret_name,
        "--project",
        project,
        "--member",
        member,
        "--role",
        "roles/secretmanager.secretAccessor",
    ])


def print_next_steps(cookie_file: Path, image: str, mount_path: str) -> None:
    print(
        f"""
Next local Docker smoke test:

  docker build -f Dockerfile.indexframe -t {image} .

  docker run --rm \\
    -v "{cookie_file}:{mount_path}:ro" \\
    -e YT_DLP_COOKIES_FILE={mount_path} \\
    -e INDEXFRAME_VARIANTS=1 \\
    {image} \\
    python -u indexframe_poc.py \\
      --url 'https://www.youtube.com/watch?v=VIDEO_ID' \\
      --out-dir /tmp/indexframe-cookie-smoke \\
      --skip-gemini

For Cloud Run, deploy/update the job so it runs indexframe_poc.py and keep
YT_DLP_COOKIES_FILE={mount_path}. Re-run this script whenever the demo account
cookies expire; it adds a new Secret Manager version and :latest will be used.
""".strip()
    )


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Refresh YouTube cookies for Indexframe yt-dlp demo")
    parser.add_argument("--project", default=os.getenv("PROJECT_ID", os.getenv("GOOGLE_CLOUD_PROJECT", "")))
    parser.add_argument("--secret-name", default=os.getenv("YOUTUBE_COOKIES_SECRET", DEFAULT_SECRET_NAME))
    parser.add_argument("--profile-dir", type=Path, default=Path(os.getenv("YOUTUBE_COOKIE_PROFILE_DIR", DEFAULT_PROFILE_DIR)))
    parser.add_argument("--cookie-file", type=Path, default=Path(os.getenv("YOUTUBE_COOKIE_FILE", DEFAULT_COOKIE_FILE)))
    parser.add_argument("--headless", action="store_true", help="Refresh an already-authenticated profile without opening a visible browser")
    parser.add_argument("--force-login", action="store_true", help="Open the Google/YouTube login URL even if an existing profile is present")
    parser.add_argument("--wait-seconds", type=float, default=3.0, help="Seconds to wait after opening YouTube before reading cookies")
    parser.add_argument("--no-install-browser", action="store_true", help="Do not auto-install Playwright Chromium if it is missing")
    parser.add_argument("--no-upload", action="store_true", help="Only write the local cookies.txt file; do not call gcloud")
    parser.add_argument("--grant-service-account", default=os.getenv("INDEXFRAME_JOB_SERVICE_ACCOUNT", ""), help="Optional Cloud Run Job service account email to grant secretAccessor")
    parser.add_argument("--update-cloud-run-job", action="store_true", help="Mount the secret into a Cloud Run Job and set YT_DLP_COOKIES_FILE")
    parser.add_argument("--job-name", default=os.getenv("CLOUD_RUN_JOB_NAME", os.getenv("JOB_NAME", "indexframe-poc")))
    parser.add_argument("--region", default=os.getenv("CLOUD_RUN_REGION", os.getenv("REGION", "us-central1")))
    parser.add_argument("--secret-mount-path", default=os.getenv("YT_DLP_COOKIES_FILE", DEFAULT_SECRET_MOUNT))
    parser.add_argument("--docker-image", default="indexframe-cookie-poc")
    parser.add_argument("--no-next-steps", action="store_true", help="Do not print local Docker smoke-test commands")
    return parser


def main() -> None:
    args = build_arg_parser().parse_args()
    cookie_file = args.cookie_file.expanduser().resolve()
    profile_dir = args.profile_dir.expanduser().resolve()
    refresh_cookie_file(
        profile_dir=profile_dir,
        cookie_file=cookie_file,
        headless=args.headless,
        force_login=args.force_login,
        wait_seconds=args.wait_seconds,
        install_browser_on_missing=not args.no_install_browser,
    )

    if not args.no_upload:
        project = require_project(args.project)
        upload_secret_version(project, args.secret_name, cookie_file)
        if args.grant_service_account:
            grant_secret_access(project, args.secret_name, args.grant_service_account)

    if not args.no_next_steps:
        print_next_steps(cookie_file, args.docker_image, args.secret_mount_path)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit(130)
