#!/usr/bin/env bash
set -euo pipefail

# Simple Cloud Run v1 PoC deploy with SMTP2GO + Secret Manager:
#   1. loads basic KEY=VALUE entries from .env without executing it
#   2. stores SMTP_PASSWORD in Secret Manager if provided
#   3. builds one container image
#   4. deploys a Cloud Run Job for async echo processing
#   5. deploys a Cloud Run service that hosts the Firebase Google sign-in UI
#
# Required in environment or .env:
#   PROJECT_ID=dev-linger
# Optional in environment or .env:
#   REGION=us-central1
#   SERVICE_NAME=indexframe-poc
#   JOB_NAME=indexframe-echo-job
#   FIREBASE_PROJECT_ID=$PROJECT_ID
#   FIREBASE_API_KEY=...                 # generated by ./deploy_firebase.sh
#   FIREBASE_AUTH_DOMAIN=$FIREBASE_PROJECT_ID.firebaseapp.com
#   FIREBASE_APP_ID=...                   # generated by ./deploy_firebase.sh
#   DISABLE_AUTH=false
#   SMTP_HOST=mail.smtp2go.com
#   SMTP_PORT=2525
#   SMTP_USERNAME=indexframe
#   SMTP_PASSWORD=<set only in shell when creating/updating the secret; do not commit it>
#   SMTP_PASSWORD_SECRET=indexframe-smtp-password
#   EMAIL_FROM=results@demo.yourdomain.com
#   EMAIL_FROM_NAME=IndexFrame Results
#   EMAIL_REPLY_TO=your-real-email@yourdomain.com
#   YOUTUBE_COOKIES_SECRET=indexframe-youtube-cookies     # created by refresh_youtube_cookies.py
#   YOUTUBE_COOKIES_MOUNT_PATH=/secrets/youtube-cookies.txt

load_dotenv_file() {
  local file="${1:-.env}"
  [[ -f "$file" ]] || return 0
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%$'\r'}"
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" == *"="* ]] || continue
    local key="${line%%=*}"
    local value="${line#*=}"
    key="$(printf '%s' "$key" | xargs)"
    [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
    # Environment variables already exported by the caller win over .env.
    if [[ -n "${!key-}" ]]; then
      continue
    fi
    # Basic .env parsing: trim outer single/double quotes only. No command execution.
    value="${value#${value%%[![:space:]]*}}"
    value="${value%${value##*[![:space:]]}}"
    if [[ "$value" =~ ^\".*\"$ || "$value" =~ ^\'.*\'$ ]]; then
      value="${value:1:${#value}-2}"
    fi
    export "$key=$value"
  done < "$file"
}

secret_exists() {
  gcloud secrets describe "$1" --project "$PROJECT_ID" >/dev/null 2>&1
}

create_or_update_secret() {
  local secret_name="$1"
  local secret_value="$2"

  if [[ -n "$secret_value" ]]; then
    local tmp
    tmp="$(mktemp)"
    chmod 600 "$tmp"
    printf '%s' "$secret_value" > "$tmp"

    if secret_exists "$secret_name"; then
      printf '\n[secret] Adding a new version to Secret Manager secret %s\n' "$secret_name"
      gcloud secrets versions add "$secret_name" \
        --data-file="$tmp" \
        --project "$PROJECT_ID" >/dev/null
    else
      printf '\n[secret] Creating Secret Manager secret %s\n' "$secret_name"
      gcloud secrets create "$secret_name" \
        --replication-policy="automatic" \
        --data-file="$tmp" \
        --project "$PROJECT_ID" >/dev/null
    fi

    rm -f "$tmp"
    unset SMTP_PASSWORD SMTP2GO_PASSWORD secret_value
    return 0
  fi

  if secret_exists "$secret_name"; then
    printf '\n[secret] Reusing existing Secret Manager secret %s\n' "$secret_name"
    return 0
  fi

  printf '\n[secret] No SMTP password was provided and secret %s does not exist.\n' "$secret_name"
  printf '         The job will deploy, but email will be logged instead of sent until the secret exists.\n'
  return 1
}

load_dotenv_file .env

PROJECT_ID="${PROJECT_ID:?Set PROJECT_ID in .env or environment}"
REGION="${REGION:-us-central1}"
SERVICE_NAME="${SERVICE_NAME:-indexframe-poc}"
JOB_NAME="${JOB_NAME:-indexframe-echo-job}"
REPOSITORY="${REPOSITORY:-indexframe}"
IMAGE_NAME="${IMAGE_NAME:-indexframe-poc}"
TAG="${TAG:-$(date +%Y%m%d%H%M%S)}"
IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${TAG}"
SERVICE_ACCOUNT_NAME="${SERVICE_ACCOUNT_NAME:-indexframe-runner}"
SERVICE_ACCOUNT="${SERVICE_ACCOUNT:-${SERVICE_ACCOUNT_NAME}@${PROJECT_ID}.iam.gserviceaccount.com}"

FIREBASE_PROJECT_ID="${FIREBASE_PROJECT_ID:-$PROJECT_ID}"
FIREBASE_AUTH_DOMAIN="${FIREBASE_AUTH_DOMAIN:-${FIREBASE_PROJECT_ID}.firebaseapp.com}"
FIREBASE_API_KEY="${FIREBASE_API_KEY:-}"
FIREBASE_APP_ID="${FIREBASE_APP_ID:-}"
DISABLE_AUTH="${DISABLE_AUTH:-false}"
DEMO_EMAIL="${DEMO_EMAIL:-}"

BUCKET_NAME="${BUCKET_NAME:-indexframe-data}"
OUTPUT_GCS_URI="${OUTPUT_GCS_URI:-gs://${BUCKET_NAME}}"

if [[ -z "$FIREBASE_API_KEY" || -z "$FIREBASE_APP_ID" ]]; then
  cat <<EOF_FIREBASE_WARN

[firebase] FIREBASE_API_KEY or FIREBASE_APP_ID is empty.
           Run ./deploy_firebase.sh first for real Google SSO, or keep DISABLE_AUTH=true for local smoke tests.
EOF_FIREBASE_WARN
fi

# SMTP2GO defaults for this PoC. The password is deployed via Secret Manager, not --set-env-vars.
SMTP_HOST="${SMTP_HOST:-mail.smtp2go.com}"
SMTP_PORT="${SMTP_PORT:-2525}"
SMTP_USERNAME="${SMTP_USERNAME:-indexframe}"
SMTP_PASSWORD_SECRET="${SMTP_PASSWORD_SECRET:-indexframe-smtp-password}"
EMAIL_FROM="${EMAIL_FROM:-}"
EMAIL_FROM_NAME="${EMAIL_FROM_NAME:-IndexFrame Results}"
EMAIL_REPLY_TO="${EMAIL_REPLY_TO:-}"
SMTP_TLS="${SMTP_TLS:-true}"

# Demo-only yt-dlp YouTube cookie support. The cookie secret is created/updated by
# refresh_youtube_cookies.py and mounted into the Cloud Run Job as a read-only file.
YOUTUBE_COOKIES_SECRET="${YOUTUBE_COOKIES_SECRET:-${YT_DLP_COOKIES_SECRET:-indexframe-youtube-cookies}}"
YOUTUBE_COOKIES_MOUNT_PATH="${YOUTUBE_COOKIES_MOUNT_PATH:-${YT_DLP_COOKIES_FILE:-/secrets/youtube-cookies.txt}}"

printf '\n[1/7] Configuring gcloud project %s\n' "$PROJECT_ID"
gcloud config set project "$PROJECT_ID" >/dev/null

printf '\n[2/7] Enabling required APIs\n'
 gcloud services enable aiplatform.googleapis.com compute.googleapis.com logging.googleapis.com cloudquotas.googleapis.com \
        cloudresourcemanager.googleapis.com iam.googleapis.com cloudbuild.googleapis.com cloudbilling.googleapis.com \
        artifactregistry.googleapis.com secretmanager.googleapis.com \
        run.googleapis.com iamcredentials.googleapis.com storage.googleapis.com \
   --project "$PROJECT_ID"

printf '\n[3/7] Ensuring Artifact Registry repo exists\n'
gcloud artifacts repositories create "$REPOSITORY" \
  --repository-format=docker \
  --location="$REGION" \
  --description="IndexFrame PoC images" \
  --project "$PROJECT_ID" >/dev/null 2>&1 || true

printf '\n[4/7] Ensuring service account exists and can run jobs\n'
gcloud iam service-accounts create "$SERVICE_ACCOUNT_NAME" \
  --display-name="IndexFrame PoC runner" \
  --project "$PROJECT_ID" >/dev/null 2>&1 || true

# create ops are async, wait for eventual update
sleep 5

gcloud projects add-iam-policy-binding "$PROJECT_ID" \
  --member="serviceAccount:${SERVICE_ACCOUNT}" \
  --role="roles/run.developer" \
  --condition=None >/dev/null

gcloud projects add-iam-policy-binding "$PROJECT_ID" \
  --member="serviceAccount:${SERVICE_ACCOUNT}" \
  --role="roles/aiplatform.user" \
  --condition=None >/dev/null

gcloud iam service-accounts add-iam-policy-binding "$SERVICE_ACCOUNT" \
  --member="serviceAccount:${SERVICE_ACCOUNT}" \
  --role="roles/iam.serviceAccountTokenCreator" \
  --project "$PROJECT_ID" >/dev/null

gcloud storage buckets create "gs://${BUCKET_NAME}" \
  --location="$REGION" \
  --project="$PROJECT_ID" >/dev/null 2>&1 || true

gcloud storage buckets add-iam-policy-binding "gs://${BUCKET_NAME}" \
  --member="serviceAccount:${SERVICE_ACCOUNT}" \
  --role="roles/storage.objectAdmin" \
  --project="$PROJECT_ID" >/dev/null

printf '\n[5/7] Creating/updating SMTP2GO password secret and checking YouTube cookies secret\n'
USE_SMTP_SECRET=false
if create_or_update_secret "$SMTP_PASSWORD_SECRET" "${SMTP_PASSWORD:-${SMTP2GO_PASSWORD:-}}"; then
  USE_SMTP_SECRET=true
  gcloud secrets add-iam-policy-binding "$SMTP_PASSWORD_SECRET" \
    --project "$PROJECT_ID" \
    --member="serviceAccount:${SERVICE_ACCOUNT}" \
    --role="roles/secretmanager.secretAccessor" >/dev/null
fi

USE_MONGODB_SECRET=false
if create_or_update_secret "$MONGODB_SECRET" "${MONGODB_URI}"; then
  USE_MONGODB_SECRET=true
  gcloud secrets add-iam-policy-binding "$MONGODB_SECRET" \
    --project "$PROJECT_ID" \
    --member="serviceAccount:${SERVICE_ACCOUNT}" \
    --role="roles/secretmanager.secretAccessor" >/dev/null
fi

USE_YOUTUBE_COOKIES_SECRET=false
if secret_exists "$YOUTUBE_COOKIES_SECRET"; then
  printf '\n[secret] Reusing YouTube cookies secret %s and mounting it at %s\n' "$YOUTUBE_COOKIES_SECRET" "$YOUTUBE_COOKIES_MOUNT_PATH"
  USE_YOUTUBE_COOKIES_SECRET=true
  gcloud secrets add-iam-policy-binding "$YOUTUBE_COOKIES_SECRET" \
    --project "$PROJECT_ID" \
    --member="serviceAccount:${SERVICE_ACCOUNT}" \
    --role="roles/secretmanager.secretAccessor" >/dev/null
else
  cat <<EOF_YT_COOKIE_WARN

[secret] YouTube cookies secret ${YOUTUBE_COOKIES_SECRET} does not exist.
         Run refresh_youtube_cookies.py first if you want yt-dlp to use authenticated cookies:
           python refresh_youtube_cookies.py --project ${PROJECT_ID} --secret-name ${YOUTUBE_COOKIES_SECRET}
         The job will deploy without YT_DLP_COOKIES_FILE and may hit YouTube bot checks.
EOF_YT_COOKIE_WARN
fi

printf '\n[6/7] Building image %s\n' "$IMAGE"
gcloud builds submit \
  --config cloudbuild.indexframe.yaml \
  --substitutions "_IMAGE=${IMAGE}" \
  --project "$PROJECT_ID" \
  .

printf '\n[7/7] Deploying Cloud Run Job and service\n'
JOB_ENV="SMTP_HOST=${SMTP_HOST},SMTP_PORT=${SMTP_PORT},SMTP_USERNAME=${SMTP_USERNAME},EMAIL_FROM=${EMAIL_FROM},EMAIL_FROM_NAME=${EMAIL_FROM_NAME},EMAIL_REPLY_TO=${EMAIL_REPLY_TO},SMTP_TLS=${SMTP_TLS},PROJECT_ID=${PROJECT_ID},OUTPUT_GCS_URI=${OUTPUT_GCS_URI},GOOGLE_SERVICE_ACCOUNT_EMAIL=${SERVICE_ACCOUNT},INDEXFRAME_MONGODB_DB=${INDEXFRAME_MONGODB_DB},INDEXFRAME_MONGODB_COLLECTION=${INDEXFRAME_MONGODB_COLLECTION}"
JOB_SECRET_VALUES=()
if [[ "$USE_SMTP_SECRET" == "true" ]]; then
  JOB_SECRET_VALUES+=("SMTP_PASSWORD=${SMTP_PASSWORD_SECRET}:latest")
fi
if [[ "$USE_MONGODB_SECRET" == "true" ]]; then
  JOB_SECRET_VALUES+=("MONGODB_URI=${MONGODB_SECRET}:latest")
fi
if [[ "$USE_YOUTUBE_COOKIES_SECRET" == "true" ]]; then
  JOB_ENV="${JOB_ENV},YT_DLP_COOKIES_FILE=${YOUTUBE_COOKIES_MOUNT_PATH}"
  JOB_SECRET_VALUES+=("${YOUTUBE_COOKIES_MOUNT_PATH}=${YOUTUBE_COOKIES_SECRET}:latest")
fi

JOB_SECRET_ARGS=()
if [[ "${#JOB_SECRET_VALUES[@]}" -gt 0 ]]; then
  JOB_SECRET_CSV="$(IFS=,; printf '%s' "${JOB_SECRET_VALUES[*]}")"
  JOB_SECRET_ARGS=(--set-secrets "$JOB_SECRET_CSV")
  echo JOB_SECRET_CSV
fi

gcloud run jobs deploy "$JOB_NAME" \
  --image "$IMAGE" \
  --region "$REGION" \
  --service-account "$SERVICE_ACCOUNT" \
  --command python \
  --args indexframe_poc.py \
  --tasks 1 \
  --max-retries 0 \
  --memory "2Gi" \
  --cpu "2" \
  --set-env-vars "$JOB_ENV" \
  "${JOB_SECRET_ARGS[@]}" \
  --project "$PROJECT_ID"

gcloud run deploy "$SERVICE_NAME" \
  --image "$IMAGE" \
  --region "$REGION" \
  --service-account "$SERVICE_ACCOUNT" \
  --allow-unauthenticated \
  --set-env-vars "PROJECT_ID=${PROJECT_ID},CLOUD_RUN_REGION=${REGION},CLOUD_RUN_JOB_NAME=${JOB_NAME},FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID},FIREBASE_API_KEY=${FIREBASE_API_KEY},FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN},FIREBASE_APP_ID=${FIREBASE_APP_ID},DISABLE_AUTH=${DISABLE_AUTH},DEMO_EMAIL=${DEMO_EMAIL}" \
  --project "$PROJECT_ID"

SERVICE_URL="$(gcloud run services describe "$SERVICE_NAME" --region "$REGION" --format='value(status.url)' --project "$PROJECT_ID")"

gcloud compute networks subnets update default \
    --region=$REGION \
    --enable-private-ip-google-access


cat <<EOF2

Done.
Service URL: ${SERVICE_URL}

SMTP2GO:
  Host: ${SMTP_HOST}
  Port: ${SMTP_PORT}
  Username: ${SMTP_USERNAME}
  Password secret: ${SMTP_PASSWORD_SECRET}
  From: ${EMAIL_FROM_NAME} <${EMAIL_FROM}>
  Reply-To: ${EMAIL_REPLY_TO:-not set}

YouTube cookies for yt-dlp:
  Secret: ${YOUTUBE_COOKIES_SECRET}
  Mounted in job: ${USE_YOUTUBE_COOKIES_SECRET}
  Mount path: ${YOUTUBE_COOKIES_MOUNT_PATH}
  Env var: YT_DLP_COOKIES_FILE=${YOUTUBE_COOKIES_MOUNT_PATH}

Firebase checklist:
  1. If needed, run ./deploy_firebase.sh to create the Firebase Web App and update .env.
  2. Enable Authentication -> Sign-in method -> Google in Firebase.
  3. Add this authorized domain in Firebase Auth settings:
     ${SERVICE_URL#https://}

Smoke test without Firebase:
  gcloud run services update ${SERVICE_NAME} --region ${REGION} --set-env-vars DISABLE_AUTH=true,MOCK_RUN_JOB_LOCALLY=false --project ${PROJECT_ID}

EOF2
